config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :npos do
    resources :subscriptions
  end
  resources :charges

  root :to => 'npos#index'
end

app/models/npo.rb
class Npo < ActiveRecord::Base

  has_many :subscriptions
  has_many :donations

  validates :name, :presence => true
  validates :account, :presence => true
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  validates :name, :presence => true
  validates :interval, :presence => true
  validates :currency, :presence => true
  validates :amount, :presence => true

  before_create :create_plan

private
  def create_plan
    Stripe.api_key = ENV['SECRET_KEY']
    Stripe::Plan.create(
      :amount => self.amount,
      :interval => self.interval,
      :name => self.name,
      :currency => self.currency,
      :id => self.name
    )
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create
    # Amount in cents
    @amount = params[:amount]
    @amount = ((@amount.to_f)*100).to_i
    @npo = params[:npo_id]

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :plan => @npo.subscription.name,
      :card  => params[:stripeToken]

    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end
end

app/controllers/npos_controller.rb
class NposController < ApplicationController

  def index
    @npos = Npo.all
  end

  def new
    @npo = Npo.new
  end

  def create
    @npo = Npo.new(npo_params)
    if @npo.save
      flash[:notice] = "Your npo was created!"
      redirect_to npos_path
    else
      render 'new'
    end
  end

  def show
    @npo = Npo.find(params[:id])
  end

  def edit
    @npo = Npo.find(params[:id])
  end

  def update
    @npo = Npo.find(params[:id])
    if @npo.update(npo_params)
      flash[:notice] = "NPO updated"
      redirect_to npos_path
    else
      render 'edit'
    end
  end

  def destroy
    @npo = Npo.find(params[:id])
    @npo.destroy
    flash[:notice]= "NPO Deleted"
    redirect_to npos_path
  end

private

  def npo_params
    params.require(:npo).permit(:name, :description, :account, :balance)

  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  def index
    @npo = Npo.find(params[:npo_id])
    @subscriptions = Subscription.all
  end

  def new
    @npo = Npo.find(params[:npo_id])
    @subscription = Subscription.new
  end

  def create
    @npo = Npo.find(params[:npo_id])
    @subscription = Subscription.new(subscription_params)
    if @subscription.save
      flash[:notice] = "Your subscription was created!"
      redirect_to npo_subscriptions_path
    else
      render 'new'
    end
  end

  def show
    @subscription = Subscription.find(params[:id])
  end

  def edit
    @subscription = Subscription.find(params[:id])
  end

  def update
    @subscription = Subscription.find(params[:id])
    if @subscription.update(subscription_params)
      flash[:notice] = "Subscription updated"
      redirect_to subscriptions_path
    else
      render 'edit'
    end
  end

  def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy
    flash[:notice]= "Subscription Deleted"
    redirect_to subscriptions_path
  end

private

  def subscription_params
    params.require(:subscription).permit(:npo_id, :interval, :currency, :name, :amount, :id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$<%=(@amount.to_f)/100%></strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <div class="field">
    <%= label_tag :amount %><br />
    <%= text_field_tag :amount, params[:amount]%>
  </div>


  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount= <%= @amount%> ></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nonprofit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <div class="navbar-brand"><%= link_to "Home", npos_path%></div>
      </div>
      <% if current_user%>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><p class="navbar-text">Logged in as <%= current_user.email%></p></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: "DELETE"%></li>
          </ul>
      <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign up", new_user_registration_path%></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Login", new_user_session_path%></li>
          </ul>
        </div>
      <% end %>
    </div>
  </nav>


<div class="container">

<%= yield %>
</div>
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/npos/_form.html.erb
<%= form_for @npo do |f| %>
  <%=f.label :name %>
  <%=f.text_field :name %>
  <%=f.label :description %>
  <%=f.text_field :description %>
  <%=f.label :account %>
  <%=f.text_field :account %>
  <%= f.submit :class => "btn btn-danger", :value => "submit" %>
<% end%>

app/views/npos/index.html.erb
<h1>NPOs</h1>

<ul>
<% @npos.each do |npo| %>
    <li><%= link_to npo.name, npo_path(npo) %></li>
  <% end %>
</ul>

<%= link_to "New npo", new_npo_path %>

app/views/npos/new.html.erb
<h1> Add a new NonProfit </h1>

<%= render 'form' %>

app/views/npos/show.html.erb
<h1>Non Profit Donations</h1>

<h2><%= @npo.name %></h2>
<p><%= @npo.description %></p>

<%= link_to "Donate", new_charge_path, :class => "btn btn-success" %>
<%= link_to "Subscribe", npo_subscriptions_path(@npo.id), :class =>"btn btn-warning"%>

app/views/subscriptions/_form.html.erb
<%= form_for [@npo, @subscription] do |f| %>
  <%=f.label :name %>
  <%=f.text_field :name %>
   <%=f.label :amount %>
  <%=f.number_field :amount %>
  <%=f.label :interval %>
  <%=f.text_field :interval, value: 'month' %>
  <%=f.label :currency %>
  <%=f.text_field :currency, value: 'usd' %>
  <%=f.hidden_field :npo_id, value: @npo.id %>
  <%= f.submit :class => "btn btn-danger", :value => "submit" %>
<% end%>

app/views/subscriptions/index.html.erb
<h1>Subscriptions</h1>

<ul>
<% @npo.subscriptions.each do |subscription| %>
    <li><%= link_to subscription.name, npo_subscription_path(@npo.id, subscription.id) %></li>
  <% end %>
</ul>

<%= link_to "New subscription", new_npo_subscription_path %>

app/views/subscriptions/new.html.erb
<%= render 'form' %>

app/views/subscriptions/show.html.erb
<h1>Show</h1>

<p>Name: <%= @subscription.name %></p>
<p>Interval: <%= @subscription.interval %></p>
<p>Amount: <%= @subscription.amount%> <%= @subscription.currency %></p>

<%= link_to "Donate", new_charge_path(:amount => @subscription.amount), :class => "btn btn-success" %>